export type JaninWeek = {
  week: number
  trimester: 1 | 2 | 3
  fruit: string
  length: string
  weight: string
  milestones: string[]
  mom: string
  normal: string
  alert: string
  tip: string
}

export const janinWeeks: JaninWeek[] = [
  { week: 2, trimester: 1, fruit: "Biji wijen", length: "~0,1 mm", weight: "< 1 g", milestones: ["Sel telur matang dan siap dibuahi di masa subur.", "Rahim menyiapkan dindingnya.", "Jika pembuahan terjadi, zigot mulai terbentuk di tuba falopi."], mom: "Bunda mungkin belum merasakan perubahan. Sebagian merasakan kram ringan atau keputihan bening saat ovulasi.", normal: "Kram ringan satu sisi dan lendir serviks bening dapat muncul saat ovulasi.", alert: "Nyeri panggul hebat atau perdarahan di luar siklus perlu diperiksa.", tip: "Catat siklus haid dan mulai konsumsi asam folat sesuai anjuran tenaga kesehatan." },
  { week: 4, trimester: 1, fruit: "Biji chia", length: "~2 mm", weight: "< 1 g", milestones: ["Embrio menempel pada dinding rahim.", "Terbentuk tiga lapisan calon organ yaitu ektoderm, mesoderm, dan endoderm.", "Plasenta awal mulai berkembang dan memproduksi hCG."], mom: "Bunda mungkin menyadari haid terlambat. Sebagian mulai merasa payudara sensitif dan cepat lelah.", normal: "Perubahan tubuh dapat terjadi pada awal kehamilan.", alert: "Perdarahan seperti haid atau lebih banyak perlu segera diperiksa.", tip: "Jika tes kehamilan positif, jadwalkan kunjungan ANC." },
  { week: 6, trimester: 1, fruit: "Kacang hijau", length: "~5 mm", weight: "< 1 g", milestones: ["Jantung mulai berdetak.", "Tabung saraf yang akan membentuk otak dan tulang belakang mulai terbentuk.", "Tunas lengan dan kaki mulai muncul."], mom: "Mual dapat mulai terasa. Payudara dapat membesar dan Bunda mungkin lebih sering buang air kecil.", normal: "Mual dan sensitif terhadap bau dapat terjadi pada awal kehamilan.", alert: "Muntah terus-menerus hingga tidak bisa makan atau minum perlu segera diperiksa.", tip: "Coba sediakan biskuit kering dan makan sedikit sebelum bangun tidur." },
  { week: 8, trimester: 1, fruit: "Buah rasberi", length: "~1,6 cm", weight: "~1 g", milestones: ["Jari tangan dan kaki mulai terbentuk.", "Kelopak mata dan ujung hidung mulai terlihat.", "Detak jantung dapat diperiksa melalui USG."], mom: "Mual dapat terasa lebih kuat. Indra penciuman Bunda mungkin lebih sensitif.", normal: "Kram ringan dapat terjadi saat rahim membesar.", alert: "Kram yang makin hebat atau darah segar perlu segera diperiksa.", tip: "Makan dalam porsi kecil tetapi lebih sering, dan jaga asupan cairan." },
  { week: 10, trimester: 1, fruit: "Stroberi", length: "~3 cm", weight: "~4 g", milestones: ["Organ vital sudah terbentuk dan mulai bekerja.", "Siku dan lutut mulai dapat ditekuk.", "Ekor embrio menghilang."], mom: "Perut bagian bawah mungkin terasa penuh. Perasaan Bunda juga dapat berubah-ubah.", normal: "Keputihan bening tanpa bau dapat meningkat selama tidak disertai gatal.", alert: "Nyeri perut tajam pada satu sisi perlu segera diperiksa.", tip: "Gunakan pakaian yang nyaman dan catat keluhan untuk dibicarakan saat kontrol ANC." },
  { week: 12, trimester: 1, fruit: "Jeruk nipis", length: "~5,4 cm", weight: "~14 g", milestones: ["Organ utama telah terbentuk.", "Janin mulai bergerak meskipun belum terasa oleh Bunda.", "Sidik jari mulai terbentuk."], mom: "Mual biasanya mulai berkurang menjelang akhir trimester pertama. Energi dan nafsu makan dapat membaik.", normal: "Garis gelap pada perut atau linea nigra dapat muncul selama kehamilan.", alert: "Perdarahan atau nyeri hebat perlu diperiksa pada usia kehamilan berapa pun.", tip: "Jadwalkan pemeriksaan ANC dan tanyakan waktu USG kepada tenaga kesehatan." },
  { week: 14, trimester: 2, fruit: "Lemon", length: "~8,7 cm", weight: "~43 g", milestones: ["Wajah makin jelas dan rambut halus mulai tumbuh.", "Janin mulai dapat mengisap jempol.", "Ginjal mulai memproduksi urine dan hati mulai bekerja."], mom: "Mual dapat mereda dan energi Bunda mungkin kembali.", normal: "Nyeri tumpul di sisi perut saat bergerak dapat terjadi saat rahim membesar.", alert: "Nyeri tajam yang terus-menerus atau flek perlu diperiksakan.", tip: "Diskusikan posisi tidur yang nyaman dengan bidan atau dokter." },
  { week: 16, trimester: 2, fruit: "Alpukat", length: "~11,6 cm", weight: "~100 g", milestones: ["Tulang mulai mengeras dari tulang rawan.", "Mata mulai bergerak di balik kelopak.", "Telinga mulai berkembang."], mom: "Sebagian Bunda mulai merasakan gerakan halus janin. Nafsu makan juga dapat meningkat.", normal: "Hidung tersumbat atau gusi berdarah ringan dapat terjadi akibat perubahan kehamilan.", alert: "Sakit kepala hebat disertai pandangan kabur perlu segera diperiksa.", tip: "Diskusikan kebutuhan zat besi dan protein saat kontrol kehamilan." },
  { week: 18, trimester: 2, fruit: "Paprika", length: "~14 cm", weight: "~190 g", milestones: ["Janin mulai mendengar suara.", "Janin bergerak, berputar, dan berguling.", "Saraf mulai dilapisi mielin."], mom: "Perut makin terlihat dan Bunda mungkin merasa pegal pada punggung bawah.", normal: "Gatal ringan pada kulit perut yang meregang dapat terasa.", alert: "Gatal hebat pada telapak tangan atau kaki perlu dikonsultasikan.", tip: "Ajak si Kecil berbicara atau putar musik lembut bila Bunda suka." },
  { week: 20, trimester: 2, fruit: "Pisang", length: "~25 cm", weight: "~300 g", milestones: ["Gerakan janin mulai terasa lebih jelas oleh sebagian Bunda.", "Rambut halus atau lanugo mulai menyelimuti tubuh.", "USG morfologi dapat dijadwalkan sesuai arahan tenaga kesehatan."], mom: "Bunda mungkin mulai merasakan kontraksi palsu yang ringan.", normal: "Perut yang mengencang sebentar lalu reda dengan istirahat dapat berupa kontraksi palsu.", alert: "Kontraksi teratur yang makin kuat sebelum 37 minggu perlu segera diperiksa.", tip: "Tanyakan jadwal USG dan pemeriksaan kehamilan berikutnya saat kontrol." },
  { week: 22, trimester: 2, fruit: "Pepaya", length: "~27 cm", weight: "~430 g", milestones: ["Alis dan bulu mata makin jelas.", "Refleks menggenggam mulai aktif.", "Janin dapat bereaksi terhadap suara keras."], mom: "Perut makin membesar. Kram kaki pada malam hari dapat mulai terasa.", normal: "Kram kaki malam hari dapat terasa; peregangan ringan bisa dicoba.", alert: "Bengkak mendadak pada wajah atau tangan disertai pusing perlu diperiksa.", tip: "Pilih aktivitas ringan yang aman dan nyaman bagi Bunda." },
  { week: 24, trimester: 2, fruit: "Jagung", length: "~30 cm", weight: "~600 g", milestones: ["Paru-paru mulai membentuk alveolus.", "Kulit masih tipis dan berkerut.", "Pola aktif dan istirahat mulai terasa lebih teratur."], mom: "Perut makin berat. Nyeri ulu hati dapat terasa setelah makan.", normal: "Heartburn setelah makan besar dapat dikurangi dengan porsi makan lebih kecil.", alert: "Pandangan kabur, nyeri ulu hati hebat, atau sakit kepala perlu diperiksa.", tip: "Tanyakan kepada bidan atau dokter tentang waktu skrining diabetes gestasional." },
  { week: 26, trimester: 2, fruit: "Selada", length: "~35 cm", weight: "~760 g", milestones: ["Mata mulai membuka dan menutup.", "Detak jantung janin makin kuat.", "Gelombang otak makin aktif merespons suara."], mom: "Bunda mungkin lebih sering buang air kecil dan merasakan sesak ringan saat beraktivitas.", normal: "Sesak ringan saat aktif dapat terasa ketika rahim menekan diafragma.", alert: "Sesak berat disertai nyeri dada atau bibir kebiruan perlu pertolongan segera.", tip: "Pilih jalan santai atau gerak ringan sesuai kondisi dan saran tenaga kesehatan." },
  { week: 28, trimester: 3, fruit: "Terong", length: "~37 cm", weight: "~1 kg", milestones: ["Mata dapat membuka.", "Gerakan janin terasa kuat dan teratur.", "Otak berkembang pesat."], mom: "Punggung dapat terasa pegal, tidur kurang nyaman, dan kaki kadang bengkak sore hari.", normal: "Bengkak ringan pada kaki yang berkurang setelah istirahat dapat terjadi.", alert: "Gerakan janin berkurang atau bengkak mendadak perlu segera diperiksa.", tip: "Tanyakan kepada bidan cara memantau gerakan janin yang sesuai." },
  { week: 30, trimester: 3, fruit: "Kubis", length: "~40 cm", weight: "~1,3 kg", milestones: ["Lemak mulai mengisi tubuh janin.", "Pola tidur dan bangun makin jelas.", "Ruang gerak janin makin sempit."], mom: "Sesak napas, heartburn, dan sering buang air kecil dapat terasa saat perut membesar.", normal: "Sering buang air kecil dapat terjadi ketika kandung kemih tertekan.", alert: "Nyeri saat buang air kecil disertai demam perlu diperiksa.", tip: "Atur waktu minum dan posisi tidur yang nyaman bersama saran tenaga kesehatan." },
  { week: 32, trimester: 3, fruit: "Kelapa", length: "~42 cm", weight: "~1,7 kg", milestones: ["Tulang makin kuat, sementara tengkorak tetap lentur.", "Sebagian besar janin mulai berada pada posisi kepala di bawah.", "Janin berlatih mengisap dan menelan air ketuban."], mom: "Kontraksi palsu dapat makin sering. Menjelang persalinan, Bunda mungkin merasa gelisah.", normal: "Kontraksi palsu dapat mereda setelah berganti posisi atau beristirahat.", alert: "Kontraksi teratur atau ketuban merembes perlu segera diperiksa.", tip: "Mulai siapkan tas persalinan dan rencana P4K bersama keluarga dan bidan." },
  { week: 34, trimester: 3, fruit: "Melon", length: "~45 cm", weight: "~2,1 kg", milestones: ["Kuku mencapai ujung jari.", "Paru-paru hampir matang.", "Lapisan lemak bertambah."], mom: "Berat badan bertambah dan tangan kadang kesemutan pada trimester akhir.", normal: "Kesemutan ringan pada tangan dapat terjadi selama kehamilan.", alert: "Kesemutan disertai bengkak wajah dan sakit kepala perlu diperiksa.", tip: "Siapkan buku KIA, identitas, kartu JKN, dan perlengkapan ibu serta bayi." },
  { week: 36, trimester: 3, fruit: "Selada romaine", length: "~47 cm", weight: "~2,7 kg", milestones: ["Kepala mulai turun ke panggul.", "Paru-paru hampir matang penuh.", "Gerakan terasa seperti dorongan karena ruang makin sempit."], mom: "Napas mungkin terasa lebih lega, tetapi tekanan panggul dan frekuensi buang air kecil dapat bertambah.", normal: "Tekanan dan nyeri tumpul di panggul dapat terasa saat kepala janin turun.", alert: "Nyeri panggul hebat hingga sulit berjalan perlu diperiksa.", tip: "Ikuti jadwal ANC yang disarankan tenaga kesehatan." },
  { week: 38, trimester: 3, fruit: "Labu kuning", length: "~49 cm", weight: "~3,1 kg", milestones: ["Janin telah mencapai usia aterm.", "Usus berisi mekonium.", "Lanugo mulai rontok dan kulit makin mulus."], mom: "Kontraksi latihan dapat terasa makin intens. Kenali tanda persalinan yang perlu diperhatikan.", normal: "Lendir kental bercampur darah dapat muncul menjelang persalinan.", alert: "Ketuban pecah, perdarahan, atau gerakan janin berkurang perlu pertolongan segera.", tip: "Pastikan keluarga mengetahui kontak bidan dan rencana transportasi." },
  { week: 40, trimester: 3, fruit: "Semangka kecil", length: "~50 cm", weight: "~3,4 kg", milestones: ["Hari perkiraan lahir tiba.", "Organ janin telah berkembang untuk berfungsi di luar rahim.", "Verniks masih melapisi kulit."], mom: "Wajar bila Bunda merasa cemas menjelang persalinan. Tidak semua bayi lahir tepat pada hari perkiraan lahir.", normal: "Lewat dari HPL beberapa hari memerlukan pemantauan bidan atau dokter.", alert: "Gerakan janin berkurang, ketuban berwarna hijau, atau perdarahan perlu pertolongan segera.", tip: "Tetap pantau gerakan janin dan ikuti anjuran tenaga kesehatan bila HPL terlewati." },
]
